### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Caden64** [mistodon/edres#2]
In the United States and other places it is illegal to use software without permission. Because no license is provided only you personally can give permission to use the software. I recommend an OSS license like MIT (Jut makes it so people can do whatever they want), GPL (Makes others abide by the license and open source their work), or BSD (different version of MIT but the software has to be listed as used). These descriptions are just my thoughts on the licenses and should not be taken as legal advice and I recommend reading the licenses in full

**Comment by mistodon** [comment]
Hey there - thanks for pointing this out. The crate is published under CC0, but I've also added a license to the repo.

I'm honestly not familiar with the legal aspect of this (especially not in the US) but I essentially waive copyright as far as possible.
